// Code generated by nug (NovelUpdates Generator). DO NOT EDIT.
package nu

type Genre string

// Genre: Total(35)
const (
	GenreAction        Genre = "8"
	GenreAdult         Genre = "280"
	GenreAdventure     Genre = "13"
	GenreComedy        Genre = "17"
	GenreDrama         Genre = "9"
	GenreEcchi         Genre = "292"
	GenreFantasy       Genre = "5"
	GenreGenderBender  Genre = "168"
	GenreHarem         Genre = "3"
	GenreHistorical    Genre = "330"
	GenreHorror        Genre = "343"
	GenreJosei         Genre = "324"
	GenreMartialArts   Genre = "14"
	GenreMature        Genre = "4"
	GenreMecha         Genre = "10"
	GenreMystery       Genre = "245"
	GenrePsychological Genre = "486"
	GenreRomance       Genre = "15"
	GenreSchoolLife    Genre = "6"
	GenreSciFi         Genre = "11"
	GenreSeinen        Genre = "18"
	GenreShoujo        Genre = "157"
	GenreShoujoAi      Genre = "851"
	GenreShounen       Genre = "12"
	GenreShounenAi     Genre = "1692"
	GenreSliceOfLife   Genre = "7"
	GenreSmut          Genre = "281"
	GenreSports        Genre = "1357"
	GenreSupernatural  Genre = "16"
	GenreTragedy       Genre = "132"
	GenreWuxia         Genre = "479"
	GenreXianxia       Genre = "480"
	GenreXuanhuan      Genre = "3954"
	GenreYaoi          Genre = "560"
	GenreYuri          Genre = "922"
)

var (
	ValueToGenre = map[string]Genre{
		"8":    GenreAction,
		"280":  GenreAdult,
		"13":   GenreAdventure,
		"17":   GenreComedy,
		"9":    GenreDrama,
		"292":  GenreEcchi,
		"5":    GenreFantasy,
		"168":  GenreGenderBender,
		"3":    GenreHarem,
		"330":  GenreHistorical,
		"343":  GenreHorror,
		"324":  GenreJosei,
		"14":   GenreMartialArts,
		"4":    GenreMature,
		"10":   GenreMecha,
		"245":  GenreMystery,
		"486":  GenrePsychological,
		"15":   GenreRomance,
		"6":    GenreSchoolLife,
		"11":   GenreSciFi,
		"18":   GenreSeinen,
		"157":  GenreShoujo,
		"851":  GenreShoujoAi,
		"12":   GenreShounen,
		"1692": GenreShounenAi,
		"7":    GenreSliceOfLife,
		"281":  GenreSmut,
		"1357": GenreSports,
		"16":   GenreSupernatural,
		"132":  GenreTragedy,
		"479":  GenreWuxia,
		"480":  GenreXianxia,
		"3954": GenreXuanhuan,
		"560":  GenreYaoi,
		"922":  GenreYuri,
	}
)

var (
	GenreToTitle = map[Genre]string{
		GenreAction:        "Action",
		GenreAdult:         "Adult",
		GenreAdventure:     "Adventure",
		GenreComedy:        "Comedy",
		GenreDrama:         "Drama",
		GenreEcchi:         "Ecchi",
		GenreFantasy:       "Fantasy",
		GenreGenderBender:  "Gender Bender",
		GenreHarem:         "Harem",
		GenreHistorical:    "Historical",
		GenreHorror:        "Horror",
		GenreJosei:         "Josei",
		GenreMartialArts:   "Martial Arts",
		GenreMature:        "Mature",
		GenreMecha:         "Mecha",
		GenreMystery:       "Mystery",
		GenrePsychological: "Psychological",
		GenreRomance:       "Romance",
		GenreSchoolLife:    "School Life",
		GenreSciFi:         "Sci-Fi",
		GenreSeinen:        "Seinen",
		GenreShoujo:        "Shoujo",
		GenreShoujoAi:      "Shoujo Ai",
		GenreShounen:       "Shounen",
		GenreShounenAi:     "Shounen Ai",
		GenreSliceOfLife:   "Slice Of Life",
		GenreSmut:          "Smut",
		GenreSports:        "Sports",
		GenreSupernatural:  "Supernatural",
		GenreTragedy:       "Tragedy",
		GenreWuxia:         "Wuxia",
		GenreXianxia:       "Xianxia",
		GenreXuanhuan:      "Xuanhuan",
		GenreYaoi:          "Yaoi",
		GenreYuri:          "Yuri",
	}
)

var (
	TitleToGenre = map[string]Genre{
		"Action":        GenreAction,
		"Adult":         GenreAdult,
		"Adventure":     GenreAdventure,
		"Comedy":        GenreComedy,
		"Drama":         GenreDrama,
		"Ecchi":         GenreEcchi,
		"Fantasy":       GenreFantasy,
		"Gender Bender": GenreGenderBender,
		"Harem":         GenreHarem,
		"Historical":    GenreHistorical,
		"Horror":        GenreHorror,
		"Josei":         GenreJosei,
		"Martial Arts":  GenreMartialArts,
		"Mature":        GenreMature,
		"Mecha":         GenreMecha,
		"Mystery":       GenreMystery,
		"Psychological": GenrePsychological,
		"Romance":       GenreRomance,
		"School Life":   GenreSchoolLife,
		"Sci-Fi":        GenreSciFi,
		"Seinen":        GenreSeinen,
		"Shoujo":        GenreShoujo,
		"Shoujo Ai":     GenreShoujoAi,
		"Shounen":       GenreShounen,
		"Shounen Ai":    GenreShounenAi,
		"Slice Of Life": GenreSliceOfLife,
		"Smut":          GenreSmut,
		"Sports":        GenreSports,
		"Supernatural":  GenreSupernatural,
		"Tragedy":       GenreTragedy,
		"Wuxia":         GenreWuxia,
		"Xianxia":       GenreXianxia,
		"Xuanhuan":      GenreXuanhuan,
		"Yaoi":          GenreYaoi,
		"Yuri":          GenreYuri,
	}
)

var (
	SlugToGenre = map[string]Genre{
		"adult":         GenreAction,
		"action":        GenreAdult,
		"adventure":     GenreAdventure,
		"comedy":        GenreComedy,
		"drama":         GenreDrama,
		"ecchi":         GenreEcchi,
		"fantasy":       GenreFantasy,
		"gender-bender": GenreGenderBender,
		"harem":         GenreHarem,
		"historical":    GenreHistorical,
		"horror":        GenreHorror,
		"josei":         GenreJosei,
		"martial-arts":  GenreMartialArts,
		"mature":        GenreMature,
		"mecha":         GenreMecha,
		"mystery":       GenreMystery,
		"psychological": GenrePsychological,
		"romance":       GenreRomance,
		"school-life":   GenreSchoolLife,
		"sci-fi":        GenreSciFi,
		"seinen":        GenreSeinen,
		"shoujo":        GenreShoujo,
		"shoujo-ai":     GenreShoujoAi,
		"shounen":       GenreShounen,
		"shounen-ai":    GenreShounenAi,
		"slice-of-life": GenreSliceOfLife,
		"smut":          GenreSmut,
		"sports":        GenreSports,
		"supernatural":  GenreSupernatural,
		"tragedy":       GenreTragedy,
		"wuxia":         GenreWuxia,
		"xianxia":       GenreXianxia,
		"xuanhuan":      GenreXuanhuan,
		"yaoi":          GenreYaoi,
		"yuri":          GenreYuri,
	}
)

var (
	GenreToSlug = map[Genre]string{
		GenreAction:        "action",
		GenreAdult:         "adult",
		GenreAdventure:     "adventure",
		GenreComedy:        "comedy",
		GenreDrama:         "drama",
		GenreEcchi:         "ecchi",
		GenreFantasy:       "fantasy",
		GenreGenderBender:  "gender-bender",
		GenreHarem:         "harem",
		GenreHistorical:    "historical",
		GenreHorror:        "horror",
		GenreJosei:         "josei",
		GenreMartialArts:   "martial-arts",
		GenreMature:        "mature",
		GenreMecha:         "mecha",
		GenreMystery:       "mystery",
		GenrePsychological: "psychological",
		GenreRomance:       "romance",
		GenreSchoolLife:    "school-life",
		GenreSciFi:         "sci-fi",
		GenreSeinen:        "seinen",
		GenreShoujo:        "shoujo",
		GenreShoujoAi:      "shoujo-ai",
		GenreShounen:       "shounen",
		GenreShounenAi:     "shounen-ai",
		GenreSliceOfLife:   "slice-of-life",
		GenreSmut:          "smut",
		GenreSports:        "sports",
		GenreSupernatural:  "supernatural",
		GenreTragedy:       "tragedy",
		GenreWuxia:         "wuxia",
		GenreXianxia:       "xianxia",
		GenreXuanhuan:      "xuanhuan",
		GenreYaoi:          "yaoi",
		GenreYuri:          "yuri",
	}
)
