// Code generated by nug (NovelUpdates Generator). DO NOT EDIT.
package nu

// Language: Total(9)
const (
	LanguageChinese    Language = "495"
	LanguageFilipino   Language = "9181"
	LanguageIndonesian Language = "9179"
	LanguageJapanese   Language = "496"
	LanguageKhmer      Language = "18657"
	LanguageKorean     Language = "497"
	LanguageMalaysian  Language = "9183"
	LanguageThai       Language = "9954"
	LanguageVietnamese Language = "9177"
)

var (
	ValueToLanguage = map[string]Language{
		"495":   LanguageChinese,
		"9181":  LanguageFilipino,
		"9179":  LanguageIndonesian,
		"496":   LanguageJapanese,
		"18657": LanguageKhmer,
		"497":   LanguageKorean,
		"9183":  LanguageMalaysian,
		"9954":  LanguageThai,
		"9177":  LanguageVietnamese,
	}
)

var (
	LanguageToTitle = map[Language]string{
		LanguageChinese:    "Chinese",
		LanguageFilipino:   "Filipino",
		LanguageIndonesian: "Indonesian",
		LanguageJapanese:   "Japanese",
		LanguageKhmer:      "Khmer",
		LanguageKorean:     "Korean",
		LanguageMalaysian:  "Malaysian",
		LanguageThai:       "Thai",
		LanguageVietnamese: "Vietnamese",
	}
)

var (
	TitleToLanguage = map[string]Language{
		"Chinese":    LanguageChinese,
		"Filipino":   LanguageFilipino,
		"Indonesian": LanguageIndonesian,
		"Japanese":   LanguageJapanese,
		"Khmer":      LanguageKhmer,
		"Korean":     LanguageKorean,
		"Malaysian":  LanguageMalaysian,
		"Thai":       LanguageThai,
		"Vietnamese": LanguageVietnamese,
	}
)

var (
	SlugToLanguage = map[string]Language{
		"chinese":    LanguageChinese,
		"filipino":   LanguageFilipino,
		"indonesian": LanguageIndonesian,
		"japanese":   LanguageJapanese,
		"khmer":      LanguageKhmer,
		"korean":     LanguageKorean,
		"malaysian":  LanguageMalaysian,
		"thai":       LanguageThai,
		"vietnamese": LanguageVietnamese,
	}
)

var (
	LanguageToSlug = map[Language]string{
		LanguageChinese:    "chinese",
		LanguageFilipino:   "filipino",
		LanguageIndonesian: "indonesian",
		LanguageJapanese:   "japanese",
		LanguageKhmer:      "khmer",
		LanguageKorean:     "korean",
		LanguageMalaysian:  "malaysian",
		LanguageThai:       "thai",
		LanguageVietnamese: "vietnamese",
	}
)
